/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'on-surface': '#0b1c30',
        'primary-fixed': '#dae2fd',
        'surface-container': '#e5eeff',
        'on-secondary-fixed-variant': '#004395',
        'secondary-fixed-dim': '#adc6ff',
        'surface-tint': '#565e74',
        surface: '#f8f9ff',
        'tertiary-container': '#191c1e',
        'surface-container-highest': '#d3e4fe',
        'surface-container-high': '#dce9ff',
        'on-tertiary-fixed-variant': '#444749',
        'on-tertiary-fixed': '#191c1e',
        'on-primary-fixed': '#131b2e',
        'on-secondary-container': '#fefcff',
        'secondary-fixed': '#d8e2ff',
        'primary-container': '#131b2e',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-primary-container': '#7c839b',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#001a42',
        'on-tertiary': '#ffffff',
        'surface-dim': '#cbdbf5',
        outline: '#76777d',
        'on-primary': '#ffffff',
        'surface-container-low': '#eff4ff',
        'on-error-container': '#93000a',
        'surface-variant': '#d3e4fe',
        'inverse-on-surface': '#eaf1ff',
        'on-primary-fixed-variant': '#3f465c',
        'surface-container-lowest': '#ffffff',
        'on-background': '#0b1c30',
        'inverse-primary': '#bec6e0',
        'surface-bright': '#f8f9ff',
        'inverse-surface': '#213145',
        'on-surface-variant': '#45464d',
        tertiary: '#000000',
        primary: '#000000',
        'on-tertiary-container': '#818486',
        'tertiary-fixed': '#e0e3e5',
        secondary: '#0058be',
        background: '#f8f9ff',
        'secondary-container': '#2170e4',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#bec6e0',
        'outline-variant': '#c6c6cd',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        '2xl': '1rem',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        xl: '64px',
        lg: '40px',
        gutter: '24px',
        sm: '16px',
        md: '24px',
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        'dashboard-gutter': '16px',
        'dashboard-card': '18px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-dashboard': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-section': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-dashboard': ['26px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-section': ['20px', { lineHeight: '1.35', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
