import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import RadioGroup from '../../../components/settings/RadioGroup';
import {
  DEFAULT_SKILL_QUIZ_QUESTION_COUNT,
  MOCK_INTERVIEW_DIFFICULTIES,
} from '../constants/interviewPrepConstants';
import { useGenerateSkillQuiz, useSkillTopics } from '../hooks/useSkillAssessment';
import AppIcon from '../../../components/icons/AppIcon';
import RetryErrorPanel from './RetryErrorPanel';
import { getApiErrorMessage } from '../utils/apiErrorUtils';

const DIFFICULTY_OPTIONS = MOCK_INTERVIEW_DIFFICULTIES.map((value) => ({
  value,
  label: value.charAt(0).toUpperCase() + value.slice(1),
}));

const QUESTION_COUNT_OPTIONS = [10, 12, 15].map((value) => ({
  value: String(value),
  label: `${value} questions`,
}));

export default function SkillAssessmentSetup() {
  const navigate = useNavigate();
  const { data: topics = [], isLoading: topicsLoading, isError: topicsError, refetch: refetchTopics } =
    useSkillTopics();
  const generateQuiz = useGenerateSkillQuiz();
  const [generateError, setGenerateError] = useState(null);

  const [topic, setTopic] = useState('');
  const [difficulty, setDifficulty] = useState('medium');
  const [questionCount, setQuestionCount] = useState(String(DEFAULT_SKILL_QUIZ_QUESTION_COUNT));

  const handleStart = async () => {
    if (!topic) {
      toast.error('Please select a topic.');
      return;
    }

    try {
      setGenerateError(null);
      const result = await generateQuiz.mutateAsync({
        topic,
        difficulty,
        questionCount: Number(questionCount),
      });

      const quizId = result.quiz?.quizId;

      if (!quizId) {
        toast.error('Could not start quiz.');
        return;
      }

      navigate(`/interview-prep/skills/${quizId}`);
    } catch (err) {
      setGenerateError(
        getApiErrorMessage(err, 'Could not generate quiz. Check your connection and try again.')
      );
    }
  };

  if (topicsError) {
    return (
      <RetryErrorPanel
        title="Could not load topics"
        message="We could not load skill topics. Check your connection and try again."
        onRetry={() => refetchTopics()}
        retryLabel="Reload topics"
      />
    );
  }

  if (topicsLoading) {
    return (
      <div className="flex justify-center py-xl">
        <AppIcon name="progress_activity" size="dashboard" spin className="text-secondary" />
      </div>
    );
  }

  const topicOptions = topics.map((t) => ({ value: t.id, label: t.label }));

  return (
    <div className="min-w-0 space-y-md">
      <header className="min-w-0">
        <h1 className="font-headline-dashboard text-headline-dashboard text-on-surface">
          Skill Assessment
        </h1>
        <p className="font-body-md text-on-surface-variant mt-base">
          Choose a topic and difficulty. Questions are generated by AI and scored on the server.
        </p>
      </header>

      <RetryErrorPanel
        message={generateError}
        onRetry={handleStart}
        retryLabel="Retry generate quiz"
      />

      <section className="dashboard-glass-card dashboard-card-padding rounded-2xl space-y-sm">
        <h2 className="font-headline-section text-headline-section">Topic</h2>
        <RadioGroup name="skill-topic" value={topic} onChange={setTopic} options={topicOptions} />
      </section>

      <section className="dashboard-glass-card dashboard-card-padding rounded-2xl space-y-sm">
        <h2 className="font-headline-section text-headline-section">Difficulty</h2>
        <RadioGroup
          name="skill-difficulty"
          value={difficulty}
          onChange={setDifficulty}
          options={DIFFICULTY_OPTIONS}
        />
      </section>

      <section className="dashboard-glass-card dashboard-card-padding rounded-2xl space-y-sm">
        <h2 className="font-headline-section text-headline-section">Length</h2>
        <RadioGroup
          name="skill-length"
          value={questionCount}
          onChange={setQuestionCount}
          options={QUESTION_COUNT_OPTIONS}
        />
      </section>

      <button
        type="button"
        onClick={handleStart}
        disabled={generateQuiz.isPending}
        className="w-full sm:w-auto px-6 py-3 rounded-xl bg-secondary text-white font-label-md hover:opacity-90 disabled:opacity-60 min-h-[44px] inline-flex items-center justify-center gap-2"
      >
        {generateQuiz.isPending ? (
          <>
            <AppIcon name="progress_activity" size="sm" spin />
            Generating quiz…
          </>
        ) : (
          'Generate & start quiz'
        )}
      </button>
    </div>
  );
}
