import {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  ArrowUpDown,
  AtSign,
  BarChart3,
  Bell,
  Bold,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleX,
  Code,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FileType,
  FilterX,
  Flag,
  Folder,
  Gift,
  GitCompare,
  GitMerge,
  Globe,
  GraduationCap,
  Heart,
  HelpCircle,
  History,
  Hourglass,
  Italic,
  Languages,
  LayoutDashboard,
  Link,
  List,
  Loader2,
  LogOut,
  Mail,
  MailOpen,
  MapPin,
  Medal,
  Menu,
  Mic,
  MoreVertical,
  Newspaper,
  NotebookPen,
  Palette,
  PenLine,
  Pencil,
  Phone,
  ScanLine,
  Search,
  Settings,
  Share2,
  Shield,
  SlidersHorizontal,
  Square,
  Target,
  Trash2,
  TrendingUp,
  Trophy,
  Underline,
  Upload,
  User,
  UserCircle,
  UserCog,
  Users,
  X,
} from 'lucide-react';

export const ICON_MAP = {
  dashboard: LayoutDashboard,
  description: FileText,
  document_scanner: ScanLine,
  mic_external_on: Mic,
  share_reviews: Share2,
  edit_note: NotebookPen,
  person: User,
  shield_lock: Shield,
  trending_up: TrendingUp,
  notifications: Bell,
  manage_accounts: UserCog,
  settings: Settings,
  help: HelpCircle,
  shield: Shield,
  logout: LogOut,
  menu: Menu,
  close: X,
  work: Briefcase,
  mail: Mail,
  location_on: MapPin,
  history: History,
  mark_email_unread: MailOpen,
  upload_file: Upload,
  model_training: Brain,
  mic: Mic,
  picture_as_pdf: FileType,
  payments: CreditCard,
  analytics: BarChart3,
  chevron_right: ChevronRight,
  error: CircleAlert,
  open_in_new: ExternalLink,
  check_circle: CircleCheck,
  visibility: Eye,
  visibility_off: EyeOff,
  progress_activity: Loader2,
  link: Link,
  code: Code,
  share: Share2,
  swap_vert: ArrowUpDown,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  arrow_back: ArrowLeft,
  palette: Palette,
  account_circle: UserCircle,
  crop_square: Square,
  delete: Trash2,
  edit: Pencil,
  call: Phone,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  more_vert: MoreVertical,
  format_bold: Bold,
  format_italic: Italic,
  format_underlined: Underline,
  format_list_bulleted: List,
  format_align_left: AlignLeft,
  format_align_center: AlignCenter,
  format_align_right: AlignRight,
  format_align_justify: AlignJustify,
  school: GraduationCap,
  target: Target,
  language: Languages,
  emoji_events: Trophy,
  favorite: Heart,
  folder: Folder,
  menu_book: BookOpen,
  military_tech: Medal,
  corporate_fare: Building2,
  article: Newspaper,
  groups: Users,
  draw: PenLine,
  tune: SlidersHorizontal,
  redeem: Gift,
  download: Download,
  filter_alt_off: FilterX,
  difference: GitCompare,
  psychology_alt: Brain,
  find_in_page: Search,
  join_inner: GitMerge,
  flag: Flag,
  calendar_today: Calendar,
  public: Globe,
  alternate_email: AtSign,
  cancel: CircleX,
  hourglass_top: Hourglass,
  photo_camera: Camera,
};

export function getLucideIcon(name) {
  return ICON_MAP[name] || null;
}
